apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubedirectorstatusbackups.kubedirector.hpe.com
spec:
  group: kubedirector.hpe.com
  version: v1beta1
  names:
    kind: KubeDirectorStatusBackup
    listKind: KubeDirectorStatusBackupList
    plural: kubedirectorstatusbackups
    singular: kubedirectorstatusbackup
    shortNames:
      - kdstatusbackup
  scope: Namespaced
  validation:
    openAPIV3Schema:
      type: object
      required: [apiVersion, kind, metadata, spec]
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            statusBackup:
              type: object
