apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kubedirectorstatusbackups.kubedirector.hpe.com
spec:
  group: kubedirector.hpe.com
  names:
    kind: KubeDirectorStatusBackup
    listKind: KubeDirectorStatusBackupList
    plural: kubedirectorstatusbackups
    singular: kubedirectorstatusbackup
    shortNames:
      - kdstatusbackup
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: [apiVersion, kind, metadata, spec]
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                statusBackup:
                  type: object
                  nullable: true
                  properties:
                    state:
                      type: string
                    restoreProgress:
                      type: object
                      nullable: true
                      properties:
                        awaitingApp:
                          type: boolean
                        awaitingStatus:
                          type: boolean
                        awaitingResources:
                          type: boolean
                        error:
                          type: string
                    memberStateRollup:
                      type: object
                      properties:
                        membershipChanging:
                          type: boolean
                        membersDown:
                          type: boolean
                        membersInitializing:
                          type: boolean
                        membersWaiting:
                          type: boolean
                        membersRestarting:
                          type: boolean
                        configErrors:
                          type: boolean
                        membersNotScheduled:
                          type: boolean
                    generationUID:
                      type: string
                    lastConnectionHash:
                      type: string  
                    specGenerationToProcess:
                      type: integer
                    clusterService:
                      type: string
                    lastNodeID:
                      type: integer
                    roles:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          statefulSet:
                            type: string
                          members:
                            type: array
                            items:
                              type: object
                              properties:
                                pod:
                                  type: string
                                nodeID:
                                  type: integer
                                service:
                                  type: string
                                pvc:
                                  type: string
                                blockDevicePaths:
                                  type: array
                                  items:
                                    type: string
                                authToken:
                                  type: string  
                                state:
                                  type: string
                                stateDetail:
                                  type: object
                                  properties:
                                    configErrorDetail:
                                      type: string
                                    lastConfigDataGeneration:
                                      type: integer
                                    lastSetupGeneration:
                                      type: integer
                                    configuringContainer:
                                      type: string
                                    lastConfiguredContainer:
                                      type: string
                                    lastKnownContainerState:
                                      type: string
                                    lastConnectionVersion:
                                      type: integer
                                    startScriptStdoutMessage:
                                      type: string
                                    startScriptStderrMessage:
                                      type: string
                                    schedulingErrorMessage:
                                      type: string
                                    pendingNotifyCmds:
                                      type: array
                                      items:
                                        type: object
                                        properties:
                                          arguments:
                                            type: array
                                            items:
                                              type: string